services:
  mysql:
    image: mysql:8.0
    container_name: mysql-bhishma
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"        # host:container
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bhisma-net

  app:
    build: .
    container_name: bhisma-app
    depends_on:
      - mysql
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-bhishma:3306/testdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_APPLICATION_NAME: bhisma
      SERVER_PORT: 9090
    networks:
      - bhisma-net

volumes:
  mysql_data:

networks:
  bhisma-net:
    driver: bridge